name = "pandazen-web-gtp"
compatibility_date = "2026-05-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "pandazen"
database_id = "replace-with-cloudflare-d1-database-id"
migrations_dir = "migrations"
