name = "pandazen-web-gtp"
compatibility_date = "2026-05-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "pandazen-cleanops-v2"
database_id = "a2beb40a-589f-40f9-940e-4d5e71654025"
migrations_dir = "migrations"
