name = "pandazen-web-gtp"
compatibility_date = "2026-05-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "pandazen"
database_id = "be338dc8-af85-4dcd-b0d3-b06e451c313e"
migrations_dir = "migrations"
